config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index', to: 'home#index'
  resources :payments, except: [:index, :show]
  resources :categories
  devise_for :users

  get 'payment_create_new/:category_id', to: 'payments#new_payment', as: 'payment_create_new'
  post 'payment_create_new/:category_id', to: 'payments#create_payment', as: 'payment_create_new_post'
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :author, class_name: 'User'

  has_many :payment_categories, dependent: :destroy
  has_many :categories, through: :payment_categories
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: %i[show edit update destroy]

  # GET /payments or /payments.json
  def index
    @payments = Payment.all.where(author_id: current_user)
  end

  # GET /payments/1 or /payments/1.json
  def show; end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit; end

  # POST /payments or /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to payment_url(@payment), notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1 or /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to payment_url(@payment), notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def new_payment
    @payment = Payment.new
    @category = Category.find(params[:category_id])
  end

  def create_payment
    @payment = Payment.new(payment_params)
    if @payment.save
      PaymentCategory.create(category_id: params[:category_id], payment_id: @payment.id)
      redirect_to category_path(id: params[:category_id]), notice: 'Transaction was successfully added.'
    else
      format.html { render :new, status: :unprocessable_entity }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_payment
    @payment = Payment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def payment_params
    params.require(:payment).permit(:name, :amount).merge(author_id: current_user.id)
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_with model: @payment, url: payments_path, method: :post do |form| %>
  <% if payment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
        <% payment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>

  <div>

  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/payments/_payment.html.erb
<div id="<%= dom_id payment %>">
  <p>
    <strong>Name:</strong>
    <%= payment.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= payment.amount %>
  </p>

</div>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render "form", payment: @payment %>

<br>

<div>
  <%= link_to "Show this payment", @payment %> |
  <%= link_to "Back to payments", payments_path %>
</div>

app/views/payments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Payments</h1>

<div id="payments">
  <% @payments.each do |payment| %>
    <%= render payment %>
    <p>
      <%= link_to "Show this payment", payment %>
    </p>
  <% end %>
</div>

<%= link_to "New payment", new_payment_path %>

app/views/payments/new.html.erb
<h1>New payment</h1>

<%= render "form", payment: @payment %>

<br>

<div>
  <%= link_to "Back to payments", payments_path %>
</div>

app/views/payments/new_payment.html.erb
<div class="d-flex flex-column align-items-center p-2">
    <h1>New Transaction</h1>
    <div id="<%= @category.icon %>" class="img_icon"></div>
    <%= form_with model: @payment, url: payment_create_new_post_path, method: :post, class: "d-flex flex-column align-items-center" do |form| %>

    <div class="form-group">
        <%= form.label :category %>
        <%= form.text_field :category, value: @category.name, disabled: true, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= form.label :amount %>
        <%= form.number_field :amount, step: 0.1, class: "form-control" %>
    </div>

    <div>
        <%= form.submit "Save", class: "btn btn-secondary mt-3" %>
    </div>

    <% end %>

</div>

app/views/payments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @payment %>

<div>
  <%= link_to "Edit this payment", edit_payment_path(@payment) %> |
  <%= link_to "Back to payments", payments_path %>

  <%= button_to "Destroy this payment", @payment, method: :delete %>
</div>