config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index', to: 'home#index'
  resources :payments, except: [:index, :show]
  resources :categories
  devise_for :users

  get 'payment_create_new/:category_id', to: 'payments#new_payment', as: 'payment_create_new'
  post 'payment_create_new/:category_id', to: 'payments#create_payment', as: 'payment_create_new_post'
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :author, class_name: 'User'

  has_many :payment_categories, dependent: :destroy
  has_many :payments, through: :payment_categories

  def total_amount_category
    payments.sum(:amount)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]
  load_and_authorize_resource

  # GET /categories or /categories.json
  def index
    @categories = Category.all.where(author_id: current_user)
  end

  # GET /categories/1 or /categories/1.json
  def show
    @category = Category.find(params[:id])
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon).merge(author_id: current_user.id)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<% if params[:action] == 'index' %>
  <div id="<%= dom_id category %>" class="d-flex justify-content-between align-items-center m-2  p-3 category_container bg_white full-width">
<% else %>
  <div id="<%= dom_id category %>" class="d-flex flex-column align-items-center m-2 p-3 full-width">
<% end %>
    <div>
      <%= link_to category do%>
        <div id="<%= category.icon %>" class="img_icon">
        </div>
      <% end %>
    </div>
    <p>
      <%= "#{category.name} " %>
    </p>
    <p class="amount">
      <%= "#{category.total_amount_category} $us" %>
    </p>


  <% if params[:action] == 'show' %>
    <table class="table table-striped mt-3">

      <tbody>
        <% @category.payments.order(created_at: :desc).each do |payment| %>
          <tr>
            <tr>
              <td><%= payment.name %></td>
            </tr>
            <tr>
              <td class="fz-12"><%= payment.created_at  %></td>
            </tr>
            <tr>
              <td class="fz-14"><%= "Total Payment    #{payment.amount} $us"  %></td>
            </tr>
          </tr>
        <% end %>
      </tbody>
      </table>
  <% end %>
</div>

app/views/categories/_form.html.erb
<%= form_with model: @category, url: categories_path, method: :post, class: "d-flex flex-column align-items-center" do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="d-flex justify-content-center flex-wrap p-2">
    <% 29.times do |i| %>
      <div class="m-1">
        <%= form.radio_button :icon, "img_icon#{i}" %>
        <%= form.label "icon_img_icon#{i}".to_sym do %>
          <%= content_tag :div, "", id: "img_icon#{i}", class: "img_icon"  %>
        <% end %>
      </div>
    <% end %>
  </div>
  <div>
    <%= form.submit "Save", class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%= link_to "<", categories_path, class: "btn btn-primary m-2" %>
<div class="d-flex flex-column align-items-center p-2">
  <h1>Editing category</h1>

  <%= render "form", category: @category %>

  <br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<div class="d-flex flex-column align-items-center bg_gray">
  <% flash.each do |type, msg| %>
        <div>
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
        </div>
  <% end %>

  <h1>Categories</h1>
  <p><%= "Total Expenses: #{@current_user.total_expenses} $us" %></p>
  <div id="categories" class="d-flex justify-content-center flex-wrap  full-width">
    <% @categories.each do |category| %>
      <%= render category %>
    <% end %>
  </div>

  <%= link_to "Add a New Category", new_category_path, :method=> :get, class: "btn-secondary mt-3 full-width btn-h link_btn" %>
</div>

app/views/categories/new.html.erb
<%= link_to "<", categories_path, class: "btn btn-primary m-2" %>
<div class="d-flex flex-column align-items-center p-2">

  <h1>New category</h1>

  <%= render "form", category: @category %>

  <br>
</div>

app/views/categories/show.html.erb
<%= link_to "<", categories_path, class: "btn btn-primary m-2" %>
<p style="color: green"><%= notice %></p>
<div class="d-flex flex-column align-items-center p-2">

  <%= render @category %>

  <div class="d-flex justify-content-center">
    <%= link_to "Edit this category", edit_category_path(@category), class: "btn-secondary link_btn m-1 rounded" %>
    <%= button_to "Add a new transaction", payment_create_new_path(params[:id]), method: :get, class: "btn-secondary  border-0 m-1 rounded" %>

    <%= button_to "Destroy this category", @category, method: :delete, class: "btn-secondary  border-0 m-1 rounded" %>
  </div>
</div>